apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod-informer
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-cnt
  restartPolicy: Always
